name: iBudget Pipeline

on:
  push:
    branches:
      - main

jobs:
  installChrome:
    runs-on: ubuntu-latest

    steps:
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

  automatedTest:
    runs-on: ubuntu-latest
    needs: installChrome

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup dotnet build
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x

      - name: Restore automated test project
        run: dotnet restore ./test/iBudget.AutomatedTest/iBudget.AutomatedTest.csproj

      - name: Build solution
        run: dotnet build ./test/iBudget.AutomatedTest/iBudget.AutomatedTest.csproj --no-restore

      - name: Automated Test
        run: dotnet test ./test/iBudget.AutomatedTest/iBudget.AutomatedTest.csproj --no-build --verbosity normal
